### ISSUE TITLE
多个页面情况下，在其他页面导航到流程图页面不显示

### ISSUE THREAD

**Issue by xylearn921** [tao12345666333/vue-jsPlumb#1]
有多个页面的情况下，在其他页面导航到流程图页面不显示流程图，点击一下浏览器刷新按钮才显示，控制台显示如图错误。
![Uploading QQ图片20170503113620.png…]()

**Comment by tao12345666333** [comment]
@xutong111  请重新上传一下图片， 你上面的图片没有上传成功~

**Comment by xylearn921** [comment]
图片还是上传不了，这么看吧http://i2.muimg.com/567571/f024a38677728aaa.png

**Comment by tao12345666333** [comment]
@xutong111   好， 看到了， 你是怎么写的呢？  可否贴段代码上来？  或者我晚上抽空给这个里面加多个页面，你到时候看看吧

**Comment by xylearn921** [comment]
好的，谢谢！这上贴图不太方便，具体出现问题的情况发邮件给你了

**Comment by sunmaer** [comment]
您好，我也遇到类似问题，请问是什么原因啊，大神

**Comment by tao12345666333** [comment]
@sunmaer  你也遇到了这样的问题吗？  你试试看 去掉keep-alive 然后重新实例化呢？

**Comment by sunmaer** [comment]
@tao12345666333 你好，我已经解决了这个问题，我把created钩子换成了mounted就可以了，因为最近学vue，具体原因还没想明白，不知道大神能否赐教下

**Comment by tao12345666333** [comment]
@sunmaer  ![Vue实例生命周期](https://cn.vuejs.org/images/lifecycle.png)  上面代码中 大致可以看做是需要有 dom 操作的  mounted 之后 vm.$el 就存在了

**Comment by sunmaer** [comment]
thanks

**Comment by sunmaer** [comment]
@tao12345666333
