### ISSUE TITLE
项目跑不起来

### ISSUE THREAD

**Issue by hhhluke** [tao12345666333/vue-jsPlumb#3]
一引用jsplumb就报错：
Cannot set property 'matchesSelector' of undefined  at eval (jsplumb.js?eac1:3126)

**Comment by tao12345666333** [comment]
@dryqiao  项目你是如何跑的呢？ `npm run dev` ?

**Comment by hhhluke** [comment]
是啊，感觉是jsplumb的问题

**Comment by tao12345666333** [comment]
麻烦提供下 node 和 npm 版本？

**Comment by shenjieming** [comment]
建议更新下 webpack 插件的东西， 或者 用~  和@ 制定版本，不然拉新的包会出现版本不兼容报错的问题

**Comment by tao12345666333** [comment]
@shenjieming  感谢建议。
